### PR TITLE
add poppler-cpp package

### PR DESCRIPTION
**Pull request by M-Waszkiewicz-Anaconda**
Add poppler-cpp package required by python-poppler

### CODE REVIEW

**Comment by skupr-anaconda** [comment]
Could you change the build number as you rebuild a package?

**Comment by cbouss** [comment]
Why can't python-poppler simply depends on poppler?

**Comment by M-Waszkiewicz-Anaconda** [comment]
> Why can't python-poppler simply depends on poppler?

does not like the poppler package, It gives an error on build

**Comment by cbouss** [comment]
> > Why can't python-poppler simply depends on poppler?
> 
> does not like the poppler package, It gives an error on build

How is this going to make it different? This new output is only a metapackage.
poppler is already a library.

python-poppler is looking for poppler-cpp: https://github.com/cbrunet/python-poppler/blob/master/meson.build#L11C27-L11C27

The poppler package includes a .pc file poppler-cpp.pc. If you add pkg-config to the build section, meson should be able to find what it needs in the poppler package itself.
Although the path inside poppler-cppp.pc seem hardcoded. This may be what need to be fixed in this feedstock.

**Comment by M-Waszkiewicz-Anaconda** [comment]
> > > Why can't python-poppler simply depends on poppler?
> > 
> > 
> > does not like the poppler package, It gives an error on build
> 
> How is this going to make it different? This new output is only a metapackage. poppler is already a library.
> 
> python-poppler is looking for poppler-cpp: https://github.com/cbrunet/python-poppler/blob/master/meson.build#L11C27-L11C27
> 
> The poppler package includes a .pc file poppler-cpp.pc. If you add pkg-config to the build section, meson should be able to find what it needs in the poppler package itself. Although the path inside poppler-cppp.pc seem hardcoded. This may be what need to be fixed in this feedstock.

yes, without this poppler-cpp, I am getting such error on python-poppler on widnows (unix builds seems fine)
Run-time dependency poppler-cpp found: NO (tried pkgconfig and cmake)
`  ..\..\meson.build:11:14: ERROR: Dependency "poppler-cpp" not found, tried pkgconfig and cmake`

Instead of patching python-poppler would not be better to add poppler-cpp and be on par with Conda Forge ?

**Review by skupr-anaconda — APPROVED** [review]
LGTM

**Review by lorepirri — APPROVED** [review]
LGTM

**Pull request merged**
